version: '3'

services:
  ros:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  command: bash -c "cd /workspaces/meso_control && source /opt/ros/foxy/setup.bash && colcon build && source ./install/setup.bash && ros2 launch launch/small.py"
  tty: true

#docker tag meso_control_ros martinpetri/meso_control
#docker push martinpetri/meso_control
#docker buildx build --platform linux/amd64,linux/arm64 -t martinpetri/meso_control:latest --push