version: '3'

services:
  ros-control:
    container_name: ros-control
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 9090:9090
    tty: true
    restart: unless-stopped

#docker tag meso_control_ros martinpetri/meso_control
#docker push martinpetri/meso_control
#docker buildx build --platform linux/amd64,linux/arm64 -t martinpetri/meso_control:latest --push