version: '3'
 
services:
  ros:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "cd /workspaces/meso_control && source /opt/ros/foxy/setup.bash && colcon build && source ./install/setup.bash && ros2 launch launch/small.py"
    tty: true